server:
  port: 8761

spring:
  application.name: service-discovery
  main:
    banner-mode: off

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF

