spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      ssl.enable: ${MAIL_SMTP_SSL_ENABLE}
      starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        default-requeue-rejected: false

app:
  rabbitmq:
    email:
      queue:
        main: email.notification.main.queue
        retry: email.notification.retry.queue
        dead: email.notification.dead.queue
      retry:
        count: 3
        delay: 5000
