spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protu-db
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver

  mail:
    host: YOUR_MAIL_HOST
    port: 2525
    username: YOUR_MAIL_USERNAME
    password: YOUR_MAIL_PASSWORD
    properties.mail.smtp:
      ssl.enable: false
      starttls.enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
