spring:
  mail:
    host: YOUR_MAIL_HOST
    port: 2525
    username: YOUR_MAIL_USERNAME
    password: YOUR_MAIL_PASSWORD
    properties.mail.smtp:
      ssl.enable: false
      starttls.enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false

