logging.level:
  org.springframework.security: INFO

spring:
  profiles:
    active: local
  application.name: notification-service
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  thymeleaf:
    check-template-location: false
