server.port: 8085
api:
  version: v1

logging.level:
  org.springframework.security: INFO
  io.lettuce.core: INFO
  com.zaxxer.hikari: INFO

spring:
  profiles:
    active: local
  application.name: user-service
  main.banner-mode: off
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.format_sql: false
    open-in-view: false
