spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      port: 6379
      host: localhost

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  jwt:
    secret: verySecureJwtSecretKeyThatIsAtLeast32BytesLong12345678901234567890
    access-token-ttl: 120000
    refresh-token-ttl: 240000

  otp:
    email-ttl: 240000
    password-ttl: 240000
    prefix:
      jwt: JWT_
      email: EMAIL_
      password: PASS_

  cloudinary:
    cloud-name: protu
    api-key: YOUR_API_KEY
    api-secret: YOUR_API_SECRET

  rabbitmq:
    email-main-queue: email.notification.main.queue
    email-retry-queue: email.notification.retry.queue

eureka:
  client:
    service-url.defaultZone:
      http://localhost:8761/eureka/