spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      ssl.enable: ${MAIL_SMTP_SSL_ENABLE}
      starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL}
  otp:
    email-ttl: ${OTP_EMAIL_TTL}
    password-ttl: ${OTP_PASSWORD_TTL}
    prefix:
      jwt: ${OTP_PREFIX_JWT}
      email: ${OTP_PREFIX_EMAIL}
      password: ${OTP_PREFIX_PASSWORD}
